<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [1]:
import torch
import math
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
def num_of_elements(t):
    if type(t)!=torch.Tensor:
        print(f"not a tensor. see the type {type(t)}")
        return
    return len(torch.flatten(t))

2.0.1
False


In [19]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x17f1536a0>


In [20]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [21]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[24., 60., 19.],
        [72., 35.,  9.]])

In [22]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.4280, 0.5172, 0.3999],
         [0.6190, 0.4591, 0.7215],
         [0.4798, 0.0522, 0.3829],
         ...,
         [0.0890, 0.6036, 0.3313],
         [0.7193, 0.2600, 0.6857],
         [0.2104, 0.9821, 0.2519]],

        [[0.5268, 0.4899, 0.4493],
         [0.8221, 0.5755, 0.1139],
         [0.5598, 0.7955, 0.7806],
         ...,
         [0.3046, 0.8472, 0.6431],
         [0.5935, 0.1386, 0.4226],
         [0.7884, 0.4996, 0.6049]],

        [[0.1228, 0.9128, 0.1091],
         [0.1957, 0.9297, 0.0655],
         [0.5345, 0.0035, 0.4794],
         ...,
         [0.8819, 0.6486, 0.0096],
         [0.7419, 0.0014, 0.2439],
         [0.8069, 0.1204, 0.6884]],

        ...,

        [[0.0868, 0.0709, 0.9433],
         [0.0403, 0.4429, 0.1102],
         [0.2234, 0.9296, 0.3387],
         ...,
         [0.7883, 0.4558, 0.9331],
         [0.9458, 0.0394, 0.1119],
         [0.7142, 0.6248, 0.3035]],

        [[0.6099, 0.9344, 0.6423],
         [0.7486, 0.7657, 0.0214],
         [0.

In [23]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [25]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.0677, 0.8132],
        [0.2942, 0.9856],
        [0.5541, 0.8044]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.4453, 0.2632],
        [0.0996, 0.4326],
        [0.1191, 0.2910]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.0301, 0.2140],
        [0.0293, 0.4264],
        [0.0660, 0.2341]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[7, 6],
        [4, 5],
        [4, 8]]) 
 torch.int64


In [26]:

print(t1[0])
print(t1[0]*t1[0])
print(t1[0])
t3=torch.rand(2,3)*100
print(t3)
print(np.int8(t3))

tensor([[3, 8, 5],
        [4, 6, 2],
        [3, 3, 7]])
tensor([[ 9, 64, 25],
        [16, 36,  4],
        [ 9,  9, 49]])
tensor([[3, 8, 5],
        [4, 6, 2],
        [3, 3, 7]])
tensor([[65.1182, 70.3372, 90.6279],
        [17.5383, 77.9241,  3.7910]])
[[65 70 90]
 [17 77  3]]


In [27]:
a=100
b=a+1
c=b+1
d=c+1
t4=torch.rand(a,b,c,d)*100
print(len(t4.flatten()))
for i in range(1000):
    t5=t4*t4
#it took 27.7 sec to do 1000 like this


106110600


In [28]:
for i in range(1000):
    t5=torch.mul(t4,t4)

1. it took 27.7 sec to do 1000 like this :t4*t4
2. it took 26.9 sec to do 100 like torch.mul(t4,t4)
3. conclusion : not  very big imporovment 

In [29]:
a1=np.arange(1,10)
a2=np.arange(10,19)
t6=torch.tensor(a1)
t7=torch.tensor(a2)
t8=(torch.mul(t6,t7))
print(f"{t6}\n{t7}\n{t8}")
t9=t8.reshape(3,3)
print(t9)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([ 10,  22,  36,  52,  70,  90, 112, 136, 162])
tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])


In [30]:


t10=torch.rand(1,8,25)
print(num_of_elements(t10))
t11=torch.rand(2,4,25)
t12=t10.reshape_as(t11)
print(t12)


200
tensor([[[0.9412, 0.9571, 0.7592, 0.9270, 0.7814, 0.3833, 0.5009, 0.6586,
          0.5318, 0.5071, 0.1846, 0.7420, 0.7092, 0.5165, 0.0907, 0.2003,
          0.5328, 0.6167, 0.1086, 0.6791, 0.2751, 0.5733, 0.9514, 0.3795,
          0.7895],
         [0.1998, 0.9101, 0.3234, 0.7946, 0.2880, 0.0629, 0.7018, 0.1722,
          0.3077, 0.8703, 0.3470, 0.2711, 0.8048, 0.3124, 0.2646, 0.9181,
          0.2741, 0.4932, 0.6740, 0.7740, 0.3788, 0.2637, 0.6498, 0.0419,
          0.9643],
         [0.9744, 0.7710, 0.6505, 0.5402, 0.6567, 0.4107, 0.4151, 0.7070,
          0.0644, 0.3535, 0.4193, 0.0756, 0.5029, 0.1597, 0.8688, 0.8202,
          0.2758, 0.0760, 0.0153, 0.5754, 0.3467, 0.1133, 0.8036, 0.6799,
          0.6210],
         [0.6270, 0.4311, 0.4099, 0.7110, 0.3218, 0.7725, 0.0048, 0.4325,
          0.2865, 0.7483, 0.8119, 0.1750, 0.9349, 0.8726, 0.8893, 0.1395,
          0.5932, 0.4111, 0.9411, 0.8289, 0.5099, 0.6629, 0.5652, 0.5626,
          0.5344]],

        [[0.3901, 0.1773, 0.91

In [31]:

a=100
b=a*10
c=b*10
d=c*10
t13=torch.rand(c,d)
t14=torch.rand(d,c)
t15=torch.matmul(t13,t14)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_2846/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [32]:
# t16=t15.clone.detach()
t16=torch.tensor(t15,dtype=torch.int32)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_10327/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t16=torch.tensor(t15,dtype=torch.int32)


In [10]:
np1=np.random.randint(1,10,(2,3))
t17=torch.tensor(np1)
# t17=t17.reshape([2,3,5])
print(t17)
print(t17.T)
tr=torch.mm(t17,t17.T)
print(tr)


tensor([[3, 4, 4],
        [5, 8, 2]])
tensor([[3, 5],
        [4, 8],
        [4, 2]])
tensor([[41, 55],
        [55, 93]])


In [34]:
#aggregtion
#1.min
t18=torch.randint(1,100,(2,3,4))
print(t18)
print(f" min: {t18.min()}\n max: {t18.max()}\n mean: {t18.mean(dtype=torch.float16)}\n meadian: {t18.median()}")

tensor([[[59, 62, 96, 93],
         [72, 78, 51, 19],
         [31, 15, 88, 47]],

        [[ 9,  8, 36, 54],
         [55, 42, 51, 66],
         [52, 13, 14, 12]]])
 min: 8
 max: 96
 mean: 46.78125
 meadian: 51


In [58]:
row=2
col=2
t20=torch.randint(0,100,(row,col))
t21=t20.clone()
# print(t20,'\n',t21)
t20[0,0]=-1
# print(t20,'\n',t21)
# print(torch.flatten(t20))
# print(torch.stack(t20,21),dim=0)
for i in range(-10,10):
    try:
        t22=torch.stack((t20,t21),dim=i)
        t23=torch.sort(torch.flatten(t22))
        print(i)
        print(t23.values)
        print(t22)
    except:
        pass


-3
tensor([-1, 13, 28, 28, 46, 46, 98, 98])
tensor([[[-1, 98],
         [46, 28]],

        [[13, 98],
         [46, 28]]])
-2
tensor([-1, 13, 28, 28, 46, 46, 98, 98])
tensor([[[-1, 98],
         [13, 98]],

        [[46, 28],
         [46, 28]]])
-1
tensor([-1, 13, 28, 28, 46, 46, 98, 98])
tensor([[[-1, 13],
         [98, 98]],

        [[46, 46],
         [28, 28]]])
0
tensor([-1, 13, 28, 28, 46, 46, 98, 98])
tensor([[[-1, 98],
         [46, 28]],

        [[13, 98],
         [46, 28]]])
1
tensor([-1, 13, 28, 28, 46, 46, 98, 98])
tensor([[[-1, 98],
         [13, 98]],

        [[46, 28],
         [46, 28]]])
2
tensor([-1, 13, 28, 28, 46, 46, 98, 98])
tensor([[[-1, 13],
         [98, 98]],

        [[46, 46],
         [28, 28]]])


In [92]:
t24=torch.randint(1,100,(3,2,1,1,4))


print(t24,t24.shape)
t24_s=t24.squeeze()
print(t24_s,t24_s.shape)


tensor([[[[[92,  8, 59, 22]]],


         [[[97, 90, 46, 73]]]],



        [[[[70, 37, 50, 17]]],


         [[[29, 62, 84, 17]]]],



        [[[[84, 22, 52, 18]]],


         [[[61, 35, 67, 18]]]]]) torch.Size([3, 2, 1, 1, 4])
tensor([[[92,  8, 59, 22],
         [97, 90, 46, 73]],

        [[70, 37, 50, 17],
         [29, 62, 84, 17]],

        [[84, 22, 52, 18],
         [61, 35, 67, 18]]]) torch.Size([3, 2, 4])


In [97]:
t24_us=t24_s.unsqueeze(dim=0)
print(t24_us,t24_us.shape)

tensor([[[[92,  8, 59, 22],
          [97, 90, 46, 73]],

         [[70, 37, 50, 17],
          [29, 62, 84, 17]],

         [[84, 22, 52, 18],
          [61, 35, 67, 18]]]]) torch.Size([1, 3, 2, 4])


In [120]:
t25=torch.arange(0,27)
t25a=t25.reshape([3,3,3])
first=t25a[0,0,0]
t25a,first,type(first)

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],
 
         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]]),
 tensor(0),
 torch.Tensor)

In [140]:
np26=np.random.randint(0,1000,[2,3,3])
t26=torch.from_numpy(np26).type(torch.float16)
t26,t26.dtype

(tensor([[[856., 510., 298.],
          [ 81., 967., 239.],
          [220., 972., 181.]],
 
         [[129., 524., 266.],
          [701., 372.,  42.],
          [962., 682., 832.]]], dtype=torch.float16),
 torch.float16)

### test
## test
# test
`sjdnjsn`


In [5]:
l=1000000
t27=torch.tensor(sorted(torch.rand(l)))
t28=torch.tensor(sorted(torch.rand(l)))
t29=(t27==t28)==True
temp=(enumerate(t29))
cnt=0
for i,v in enumerate(t29):
    
    if v:
        cnt+=1
        print(i,t27[i])
print(f"number of identical pairs: {cnt}")


577071 tensor(0.5773)
613980 tensor(0.6141)
691228 tensor(0.6913)
691285 tensor(0.6913)
692049 tensor(0.6921)
692056 tensor(0.6921)
722057 tensor(0.7221)
723060 tensor(0.7232)
723573 tensor(0.7237)
738473 tensor(0.7387)
738474 tensor(0.7387)
739934 tensor(0.7401)
739998 tensor(0.7402)
739999 tensor(0.7402)
number of identical pairs: 14


In [28]:
torch.manual_seed(40)
t30=torch.rand(2,3)
torch.manual_seed(40)
t31=torch.rand(2,3)
print(f"{t30}\n{t31}")

tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878]])
tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878]])
